/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core.views;

import core.models.Calculator;
import core.storage.History;
import core.models.Operation;
import java.math.RoundingMode;
import java.math.BigDecimal;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author edangulo
 */
public class CalculatorFrame extends javax.swing.JFrame {

    private History history;

    /**
     * Creates new form Calculator
     */
    public CalculatorFrame() {
        this.history = new History();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L1Title = new javax.swing.JLabel();
        B1Add = new javax.swing.JButton();
        B2Subtract = new javax.swing.JButton();
        B3Multiply = new javax.swing.JButton();
        B4Divide = new javax.swing.JButton();
        B5Potency = new javax.swing.JButton();
        B6Clear = new javax.swing.JButton();
        B7Update = new javax.swing.JButton();
        TF1Number1 = new javax.swing.JTextField();
        TF2Number2 = new javax.swing.JTextField();
        L2Title = new javax.swing.JLabel();
        L3Title = new javax.swing.JLabel();
        L4Title = new javax.swing.JLabel();
        SPanelUpdate = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        TF3Result = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        L1Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L1Title.setText("Calculator");

        B1Add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B1Add.setText("Add");
        B1Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1AddActionPerformed(evt);
            }
        });

        B2Subtract.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B2Subtract.setText("Subtract");
        B2Subtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2SubtractActionPerformed(evt);
            }
        });

        B3Multiply.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B3Multiply.setText("Multiply");
        B3Multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3MultiplyActionPerformed(evt);
            }
        });

        B4Divide.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B4Divide.setText("Divide");
        B4Divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4DivideActionPerformed(evt);
            }
        });

        B5Potency.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B5Potency.setText("Potency");
        B5Potency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5PotencyActionPerformed(evt);
            }
        });

        B6Clear.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        B6Clear.setText("Clear numbers");
        B6Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ClearActionPerformed(evt);
            }
        });

        B7Update.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        B7Update.setText("Update history");
        B7Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7UpdateActionPerformed(evt);
            }
        });

        TF1Number1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        TF2Number2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        L2Title.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        L2Title.setText("Number 1");

        L3Title.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        L3Title.setText("Number 2");

        L4Title.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        L4Title.setText("Result");

        jList1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jList1.setEnabled(false);
        SPanelUpdate.setViewportView(jList1);

        TF3Result.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TF3Result.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF3Result.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B6Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(L4Title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(L2Title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(L3Title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TF1Number1)
                            .addComponent(TF2Number2)
                            .addComponent(TF3Result, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(B5Potency, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B3Multiply, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(B1Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(B2Subtract, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(B4Divide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B7Update, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(SPanelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(L1Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L1Title)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L2Title)
                    .addComponent(TF1Number1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B7Update))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L3Title)
                            .addComponent(TF2Number2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L4Title)
                            .addComponent(TF3Result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B1Add)
                            .addComponent(B2Subtract))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B4Divide)
                            .addComponent(B3Multiply))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B5Potency)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B6Clear))
                    .addComponent(SPanelUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1AddActionPerformed
        // TODO add your handling code here:
        try {
            Calculator calculator = new Calculator();

            double number1 = Double.parseDouble(TF1Number1.getText());
            double number2 = Double.parseDouble(TF2Number2.getText());
            double result = calculator.add(number1, number2);

            this.history.addOperation(new Operation(number1, number2, "+", result));

            TF3Result.setText("" + result);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_B1AddActionPerformed

    private void B2SubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2SubtractActionPerformed
        // TODO add your handling code here:
        try {
            Calculator calculator = new Calculator();

            double number1 = Double.parseDouble(TF1Number1.getText());
            double number2 = Double.parseDouble(TF2Number2.getText());
            double result = calculator.subtract(number1, number2);

            this.history.addOperation(new Operation(number1, number2, "-", result));

            TF3Result.setText("" + result);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_B2SubtractActionPerformed

    private void B3MultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3MultiplyActionPerformed
        // TODO add your handling code here:
        try {
            Calculator calculator = new Calculator();

            double number1 = Double.parseDouble(TF1Number1.getText());
            double number2 = Double.parseDouble(TF2Number2.getText());
            double result = calculator.multiply(number1, number2);

            this.history.addOperation(new Operation(number1, number2, "*", result));

            TF3Result.setText("" + result);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_B3MultiplyActionPerformed

    private void B4DivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4DivideActionPerformed
        // TODO add your handling code here:
        try {
            Calculator calculator = new Calculator();

            double number1 = Double.parseDouble(TF1Number1.getText());
            double number2 = Double.parseDouble(TF2Number2.getText());
            double result = calculator.divide(number1, number2);

            this.history.addOperation(new Operation(number1, number2, "/", result));

            TF3Result.setText("" + result);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_B4DivideActionPerformed

    private void B5PotencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5PotencyActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Not Implemented", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_B5PotencyActionPerformed

    private void B6ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ClearActionPerformed
        // TODO add your handling code here:
        TF1Number1.setText("");
        TF2Number2.setText("");
        TF3Result.setText("");
    }//GEN-LAST:event_B6ClearActionPerformed

    private void B7UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7UpdateActionPerformed
        // TODO add your handling code here:
        ArrayList<Operation> operationHistory = this.history.getOperations();
        Collections.reverse(this.history.getOperations());

        DefaultListModel model = new DefaultListModel();
        model.addAll(operationHistory);
        jList1.setModel(model);
    }//GEN-LAST:event_B7UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1Add;
    private javax.swing.JButton B2Subtract;
    private javax.swing.JButton B3Multiply;
    private javax.swing.JButton B4Divide;
    private javax.swing.JButton B5Potency;
    private javax.swing.JButton B6Clear;
    private javax.swing.JButton B7Update;
    private javax.swing.JLabel L1Title;
    private javax.swing.JLabel L2Title;
    private javax.swing.JLabel L3Title;
    private javax.swing.JLabel L4Title;
    private javax.swing.JScrollPane SPanelUpdate;
    private javax.swing.JTextField TF1Number1;
    private javax.swing.JTextField TF2Number2;
    private javax.swing.JTextField TF3Result;
    private javax.swing.JList<String> jList1;
    // End of variables declaration//GEN-END:variables
}
